<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SQL Injection</title>

    <link rel="stylesheet" type="text/css" href="assets/css/app.css">
    <link rel="stylesheet" type="text/css" href="assets/css/bootstrap.css">

    <script rel="script" type="application/javascript" src="assets/js/jquery-3.3.1.min.js"></script>
    <script rel="script" type="application/javascript" src="assets/js/bootstrap.js"></script>
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="#">IT-Fabrik</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Software</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" href="#">Betriebssysteme</a>
                        <a class="dropdown-item" href="#">Brennprogramme</a>
                        <a class="dropdown-item" href="#">Audioprogramme</a>
                        <a class="dropdown-item" href="#">Office</a>
                        <a class="dropdown-item" href="#">Sicherheit</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Hardware</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" href="#">Rechner</a>
                        <a class="dropdown-item" href="#">Mainboards</a>
                        <a class="dropdown-item" href="#">Grafikkarte</a>
                        <a class="dropdown-item" href="#">Monitore</a>
                        <a class="dropdown-item" href="#">Netzteile</a>
                        <a class="dropdown-item" href="#">Gehäuse</a>
                        <a class="dropdown-item" href="#">Arbeitsspeicher</a>
                        <a class="dropdown-item" href="#">Prozessoren</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Unsere Angebote</a>
                </li>
            </ul>
        </div>
    </div>

</nav>

<div class="container-fluid px-0">
    <div class="jumbotron p-4 p-md-5 text-white bg-dark rounded-0">
        <div class="container">
            <div class="col-md-6 px-0">
                <h1 class="display-4 font-italic">IT-Fabrik Onlineshop</h1>
                <p class="lead my-3">Die IT-Fabrik hat nun einen Online-Shop für Software- und Hardware-Zubehör. Werde noch heute Kunde und erhalte 10% Rabatt auf unsere Waren.</p>
                <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">weiterlesen...</a></p>
            </div>
        </div>
    </div>
<!--    <img src="assets/images/logo.jpg" style="width: 100%; height: 600px;">-->
</div>

<div class="container">
    <form>
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Artikel suchen..." aria-label="search" aria-describedby="button-addon2">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="button-addon2">Search</button>
            </div>
        </div>
    </form>

    <div class="card">
        <div class="card-header">
            Test
        </div>
        <div class="card-body">
            Test
        </div>
    </div>

    Hallo, <?php echo $arguments['result']; ?>
</div>
</body>
</html>