<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Informationssicherheit</title>

    <link rel="stylesheet" type="text/css" href="assets/css/app.css">
    <link rel="stylesheet" type="text/css" href="assets/css/bootstrap.css">

    <script rel="script" type="application/javascript" src="assets/js/jquery-3.3.1.min.js"></script>
    <script rel="script" type="application/javascript" src="assets/js/bootstrap.js"></script>
</head>
<body style="height: 100%; margin: 0;">
<div class="welcomeTeaser">
    <div class="welcomeTeaser after"></div>

    <div class="welcomeTeaser-inner">
        <div class="welcomeTeaser__description">
            <div class="container">
                <div class="welcomeTeaser__description-headline">
                    <h1 class="text-center">Informationssicherheit</h1>
                </div>
            </div>
            <div class="welcomeTeaser__description-text">
                <p class="text-center">
                    <a href="example-1.php">Beispiel 1</a>
                    <a href="example-2.php">Beispiel 2</a>
                </p>
            </div>
        </div>
    </div>
</div>
</body>
</html>